BREAST CANCER PREDICTION


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
breast = pd.read_csv("data.csv")
breast.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [6]:
breast.shape

(569, 33)

In [7]:
breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [8]:
breast.duplicated().sum()

np.int64(0)

In [9]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [10]:
breast.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [11]:
breast_numeric = breast.select_dtypes(include=['number'])
breast_numeric.corr()


id  radius_mean  texture_mean  perimeter_mean  \
id                       1.000000     0.074626      0.099770        0.073159   
radius_mean              0.074626     1.000000      0.323782        0.997855   
texture_mean             0.099770     0.323782      1.000000        0.329533   
perimeter_mean           0.073159     0.997855      0.329533        1.000000   
area_mean                0.096893     0.987357      0.321086        0.986507   
smoothness_mean         -0.012968     0.170581     -0.023389        0.207278   
compactness_mean         0.000096     0.506124      0.236702        0.556936   
concavity_mean           0.050080     0.676764      0.302418        0.716136   
concave points_mean      0.044158     0.822529      0.293464        0.850977   
symmetry_mean           -0.022114     0.147741      0.071401        0.183027   
fractal_dimension_mean  -0.052511    -0.311631     -0.076437       -0.261477   
radius_se                0.143048     0.679090      0.275869        0.691765   
texture_se              -0.007526    -0.097317      0.386358       -0.086761   
perimeter_se             0.137331     0.674172      0.281673        0.693135   
area_se                  0.177742     0.735864      0.259845        0.744983   
smoothness_se            0.096781    -0.222600      0.006614       -0.202694   
compactness_se           0.033961     0.206000      0.191975        0.250744   
concavity_se             0.055239     0.194204      0.143293        0.228082   
concave points_se        0.078768     0.376169      0.163851        0.407217   
symmetry_se             -0.017306    -0.104321      0.009127       -0.081629   
fractal_dimension_se     0.025725    -0.042641      0.054458       -0.005523   
radius_worst             0.082405     0.969539      0.352573        0.969476   
texture_worst            0.064720     0.297008      0.912045        0.303038   
perimeter_worst          0.079986     0.965137      0.358040        0.970387   
area_worst               0.107187     0.941082      0.343546        0.941550   
smoothness_worst         0.010338     0.119616      0.077503        0.150549   
compactness_worst       -0.002968     0.413463      0.277830        0.455774   
concavity_worst          0.023203     0.526911      0.301025        0.563879   
concave points_worst     0.035174     0.744214      0.295316        0.771241   
symmetry_worst          -0.044224     0.163953      0.105008        0.189115   
fractal_dimension_worst -0.029866     0.007066      0.119205        0.051019   
Unnamed: 32                   NaN          NaN           NaN             NaN   

                         area_mean  smoothness_mean  compactness_mean  \
id                        0.096893        -0.012968          0.000096   
radius_mean               0.987357         0.170581          0.506124   
texture_mean              0.321086        -0.023389          0.236702   
perimeter_mean            0.986507         0.207278          0.556936   
area_mean                 1.000000         0.177028          0.498502   
smoothness_mean           0.177028         1.000000          0.659123   
compactness_mean          0.498502         0.659123          1.000000   
concavity_mean            0.685983         0.521984          0.883121   
concave points_mean       0.823269         0.553695          0.831135   
symmetry_mean             0.151293         0.557775          0.602641   
fractal_dimension_mean   -0.283110         0.584792          0.565369   
radius_se                 0.732562         0.301467          0.497473   
texture_se               -0.066280         0.068406          0.046205   
perimeter_se              0.726628         0.296092          0.548905   
area_se                   0.800086         0.246552          0.455653   
smoothness_se            -0.166777         0.332375          0.135299   
compactness_se            0.212583         0.318943          0.738722   
concavity_se              0.207660         0.248396          0.570517   
con

In [12]:
breast.drop('Unnamed: 32',axis = 1,inplace= True)

ENCODING THE TRAGET VARIABLE

In [14]:
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()

In [15]:
breast['diagnosis'] = breast['diagnosis'].map({"M" : 1 ,"B": 0})

In [16]:
breast

id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
0      842302          1        17.99         10.38          122.80   
1      842517          1        20.57         17.77          132.90   
2    84300903          1        19.69         21.25          130.00   
3    84348301          1        11.42         20.38           77.58   
4    84358402          1        20.29         14.34          135.10   
..        ...        ...          ...           ...             ...   
564    926424          1        21.56         22.39          142.00   
565    926682          1        20.13         28.25          131.20   
566    926954          1        16.60         28.08          108.30   
567    927241          1        20.60         29.33          140.10   
568     92751          0         7.76         24.54           47.92   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0       1001.0          0.11840           0.27760         0.30010   
1       1326.0          0.08474           0.07864         0.08690   
2       1203.0          0.10960           0.15990         0.19740   
3        386.1          0.14250           0.28390         0.24140   
4       1297.0          0.10030           0.13280         0.19800   
..         ...              ...               ...             ...   
564     1479.0          0.11100           0.11590         0.24390   
565     1261.0          0.09780           0.10340         0.14400   
566      858.1          0.08455           0.10230         0.09251   
567     1265.0          0.11780           0.27700         0.35140   
568      181.0          0.05263           0.04362         0.00000   

     concave points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                0.14710  ...        25.380          17.33           184.60   
1                0.07017  ...        24.990          23.41           158.80   
2                0.12790  ...        23.570          25.53           152.50   
3                0.10520  ...        14.910          26.50            98.87   
4                0.10430  ...        22.540          16.67           152.20   
..                   ...  ...           ...            ...              ...   
564              0.13890  ...        25.450          26.40           166.10   
565              0.09791  ...        23.690          38.25           155.00   
566              0.05302  ...        18.980          34.12           126.70   
567              0.15200  ...        25.740          39.42           184.60   
568              0.00000  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0

In [17]:
breast['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

SPLIITING DATA INTO TRAINING AND TESTING SETS

In [19]:
X = breast.drop('diagnosis',axis = 1)
y = breast['diagnosis']

In [20]:

X.shape

(569, 31)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [23]:
X_train.shape

(381, 31)

In [24]:
X_test.shape

(188, 31)

FEATURE SCALING

In [26]:
X_train

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
172    87164       15.460         11.89          102.50      736.9   
407   905190       12.850         21.37           82.63      514.5   
56    857637       19.210         18.57          125.50     1152.0   
497   914580       12.470         17.31           80.45      480.1   
301   892604       12.460         19.89           80.43      471.3   
..       ...          ...           ...             ...        ...   
71    859711        8.888         14.64           58.79      244.0   
106   863031       11.640         18.33           75.17      412.5   
270  8910721       14.290         16.82           90.30      632.6   
435   908489       13.980         19.62           91.12      599.5   
102   862965       12.180         20.52           77.22      458.7   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
172          0.12570           0.15550         0.20320              0.10970   
407          0.07551           0.08316         0.06126              0.01867   
56           0.10530           0.12670         0.13230              0.08994   
497          0.08928           0.07630         0.03609              0.02369   
301          0.08451           0.10140         0.06830              0.03099   
..               ...               ...             ...                  ...   
71           0.09783           0.15310         0.08606              0.02872   
106          0.11420           0.10170         0.07070              0.03485   
270          0.06429           0.02675         0.00725              0.00625   
435          0.10600           0.11330         0.11260              0.06463   
102          0.08013           0.04038         0.02383              0.01770   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
172         0.1966  ...        18.790          17.04           125.00   
407         0.1580  ...        14.400          27.01            91.63   
56          0.1917  ...        26.140          28.14           170.10   
497         0.1526  ...        14.060          24.34            92.82   
301         0.1781  ...        13.460          23.07            88.13   
..             ...  ...           ...            ...              ...   
71          0.1902  ...         9.733          15.67            62.56   
106         0.1801  ...        13.140          29.26            85.51   
270         0.1508  ...        14.910          20.65            94.44   
435         0.1669  ...        17.040          30.80           113.90   
102         0.1739  ...        13.340          32.84            84.58   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
172      1102.0           0.15310            0.35830          0.58300   
407       645.8           0.09402            0.19360          0.18380   
56       2145.0           0.16240            0.35110          0.38790   
497       607.3           0.12760            0.25060          0.20280   
301       551.3           0.10500            0.21580          0.19040   
..          ...               ...                ...              ...   
71        284.4           0.12070            0.24360          0.14340   
106       521.7           0.16880            0.26600          0.28730   
270       684.6           0.08567            0.05036          0.03866   
435       869.3           0.16130            0.35680          0.40690   
102       547.8           0.11230            0.08862          0.11450   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
172               0.18270          0.3216                  0.10100  
407               0.05601          0.2488                  0.08151  
56                0.20910          0.3537                  0.08294  
497               0.10530          0.3035                  0.07661  
301               0.07625          0.2685                  0.07764  
..                    ...             ...           

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [28]:
sc.fit(X_train)

StandardScaler()

In [29]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [30]:
X_train

array([[-0.23841709,  0.35581987, -1.72664707, ...,  1.05652305,
         0.51844283,  0.98925483],
       [-0.23209947, -0.37326674,  0.50881308, ..., -0.89667412,
        -0.63236707, -0.11469617],
       [-0.23246672,  1.4033581 , -0.15144941, ...,  1.46353548,
         1.02587412, -0.03369823],
       ...,
       [-0.17027269,  0.02898794, -0.56411347, ..., -1.2463348 ,
        -0.67979055, -1.26509354],
       [-0.23207399, -0.05760855,  0.09614902, ...,  1.05652305,
         0.45995387,  1.24414347],
       [-0.23242557, -0.5604269 ,  0.30837625, ..., -0.6145405 ,
        -0.30672581, -0.8357478 ]], shape=(381, 31))

TRAINING MODEL

In [32]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [33]:
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)

In [34]:
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_test,y_pred)

0.9787234042553191

PREDICTION SYSTEM

In [38]:
input_text = (([-0.17181512, -0.28946368, -0.91310935, -0.28575581, -0.33748097,
       -0.15922578, -0.36141191,  0.04977328, -0.3664951 ,  0.06374044,
       -0.08184529, -0.46276134, -0.79280769, -0.49988432, -0.36533669,
        0.47741314, -0.2878879 , -0.06473128, -0.38668234,  0.88487431,
       -0.12089923, -0.31610314, -0.83680516, -0.29333859, -0.35965894,
        0.6920716 , -0.15860915,  0.15520854, -0.26133388,  1.51907836,
        0.15831788]))
np_df = np.asarray(input_text)
prediciont = lg.predict(np_df.reshape(1,-1))

if prediciont[0] == 1:
    print("Cancrous")
else:
    print("not Cancrous")

not Cancrous


In [39]:
import pickle
pickle.dump(lg,open('model.pkl','wb'))

In [40]:
X_train[10]

array([-0.23250538,  0.82511699, -0.66315284,  0.96181678,  0.68936555,
        1.63561451,  2.39991193,  1.6966724 ,  2.38986091,  4.55838605,
        1.57967131,  2.17560637, -0.44389265,  2.04714969,  1.41945307,
        0.30152063,  0.69125126,  0.15943153,  1.89652406,  0.31709006,
        1.35315121,  1.22293769, -0.68774672,  1.33901374,  0.99404377,
        0.98161345,  0.96612202,  0.57891167,  2.1711821 ,  1.86210823,
        1.26680023])

In [76]:
X_test[10]

array([-0.16871537, -0.27270307,  1.42374824, -0.33494326, -0.34022801,
       -0.58908858, -0.99898304, -0.77652734, -0.73699418, -0.68536716,
       -0.94015777, -0.67587337,  0.26802348, -0.73559115, -0.47027692,
       -0.41504327, -0.95207613, -0.56770683, -0.8746754 , -0.86651227,
       -0.73468417, -0.40251987,  1.43716425, -0.48362559, -0.43635206,
       -0.12469571, -0.95116927, -0.65755848, -0.83438888, -0.70192151,
       -0.88672552])

In [78]:
X_test[1]

array([-0.23245175,  1.32793534,  0.4946646 ,  1.27076274,  1.28629906,
       -0.43106144, -0.0144555 ,  0.24073096,  0.80339173, -0.82190401,
       -1.10961593,  1.30000872, -0.7836708 ,  1.21167399,  1.11027213,
       -0.8346499 , -0.4884411 , -0.31932789,  0.27198964, -0.81847846,
       -0.78301369,  1.75995595,  0.17016745,  1.74165866,  1.69360942,
       -0.53956164, -0.10546178, -0.00644123,  0.99793792, -0.53277775,
       -0.99944294])